#!/usr/bin/env bash
if [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
  "$(dirname "$0")/k.bat" "$@"
else
  source "$(dirname "$0")/setenv"
  ulimit -s `ulimit -H -s`
  eval $JAVA -Xmx16G -XX:-UseGCOverheadLimit org.kframework.main.Main '"$@"'
fi
